--使用hncs_creatorepp_new用户执行

create or replace trigger creatorepp_new.TRI_TA_SP_INSTANCE --创建触发器
/**
 *<p>Title:</p>
 *<p>Description:触发器实现将审批办件数据插入和更新到总库</p>
 *<p>Copyright:Copyright (c) 2019</p>
 *<p>Company:湖南科创</p>
 *@author feiwen.liu
 *@version 1.0
 *@date 2019-5-29
 *@midify by
 *@midify date
 *@midify content
 */
after insert or update --在数据库动作之后触发器执行（插入和更新操作）
--of INSTANCE_CODE,INSTANCE_NAME,ACCEPT_NAME,ACCEPT_TIME,END_NAME,END_TIME,APPLY_ID,ORG_ID,PROJECT_STATE,
--NOTACCEPT_REASON,CORRECTION_TIME,APPROVE_ID,INSTANCE_SOURCE,SUBMIT_TIME,ACCEPT_ID,END_ID,IS_SENDRESULT,
--IS_WLTS,ACCEPT_ORG_ID,APPLYER_TYPE,RESULT_TYPE
ON TA_SP_INSTANCE -- 审批实例表
FOR EACH ROW -- 每一行记录都执行
DECLARE  count_num number; -- 总库办件数
         errorcode number;
         errorinfo varchar2(200);
         is_sussess number;
BEGIN
    --0:非暂存、20:并联暂存、21:并联分发、22:一件事一次办暂存：23:一件事一次办分发;24:并联分发至第三方系统(望城) 的数据才能进入总库
    IF(:NEW.PROJECT_STATE NOT IN ('0','20','22','23','24')) THEN

        SELECT COUNT(1) INTO count_num FROM SUPERVISE.TA_SP_INSTANCE I WHERE I.INSTANCE_ID = :NEW.INSTANCE_ID;

        IF(count_num=0) THEN
            INSERT INTO SUPERVISE.TA_SP_INSTANCE(INSTANCE_ID,INSTANCE_CODE,APPROVE_CODE,INSTANCE_NAME,INSTANCE_PY,ACCEPT_NAME,
            ACCEPT_TIME,END_NAME,END_TIME,APPLY_ID,APPLY_TYPE,APPLY_NAME,ORG_ID,AREA_CODE,PROJECT_STATE,QUEUE_CODE,QUERY_CODE,
            NOTACCEPT_REASON,CORRECTION_TIME,APPROVE_ID,INSTANCE_SOURCE,SUBMIT_TIME,REMARK,PRE_REASON,APPROVE_NAME,ACCEPT_ID,END_ID,
            ORG_NAME,CUR_TACHE,IS_SENDRESULT,RZ_APPLY_ID,IS_WLTS,TRANSACTOR_ID,IS_EXCHANGE,
            ACCEPT_ORG_ID,ACCEPT_AREA_CODE,IS_HELPAGENCY,MOD_FLAG,PRETRIAL_TIME,BATCH_ID,DUE_TIME,
            ORG_SOCIAL_CREDIT_NO,APPLYER_TYPE,RESULT_TYPE,RIGHTS_CODE,TASKHANDLEITEM,TRANS_TYPE,TRANSACTION_FROM,LOCALCATALOGCODE,
            LOCALTASKCODE,VERSION_NUM,SJDJ_IS_DISTRIBUTE,
            SJDJ_DISTRIBUTE_MODE,SJDJ_DISTRIBUTE_ACCOUNT)
            SELECT :NEW.INSTANCE_ID,:NEW.INSTANCE_CODE,:NEW.APPROVE_CODE,:NEW.INSTANCE_NAME,:NEW.INSTANCE_PY,:NEW.ACCEPT_NAME,
            :NEW.ACCEPT_TIME,:NEW.END_NAME,:NEW.END_TIME,:NEW.APPLY_ID,:NEW.APPLY_TYPE,:NEW.APPLY_NAME,:NEW.ORG_ID,:NEW.AREA_CODE,:NEW.PROJECT_STATE,:NEW.QUEUE_CODE,:NEW.QUERY_CODE,
            :NEW.NOTACCEPT_REASON,:NEW.CORRECTION_TIME,:NEW.APPROVE_ID,:NEW.INSTANCE_SOURCE,:NEW.SUBMIT_TIME,:NEW.REMARK,:NEW.PRE_REASON,:NEW.APPROVE_NAME,:NEW.ACCEPT_ID,:NEW.END_ID,
            :NEW.ORG_NAME,:NEW.CUR_TACHE,:NEW.IS_SENDRESULT,:NEW.RZ_APPLY_ID,:NEW.IS_WLTS,:NEW.TRANSACTOR_ID,'N',
            :NEW.ACCEPT_ORG_ID,:NEW.ACCEPT_AREA_CODE,:NEW.IS_HELPAGENCY,'N',:NEW.PRETRIAL_TIME,:NEW.BATCH_ID,:NEW.DUE_TIME,
            :NEW.ORG_SOCIAL_CREDIT_NO,:NEW.APPLYER_TYPE,:NEW.RESULT_TYPE,:NEW.RIGHTS_CODE,:NEW.TASKHANDLEITEM,:NEW.TRANS_TYPE,:NEW.TRANSACTION_FROM,:NEW.LOCALCATALOGCODE,
            :NEW.LOCALTASKCODE,:NEW.VERSION_NUM,DECODE(A.IS_DISTRIBUTE,NULL,'Y',A.IS_DISTRIBUTE) SJDJ_IS_DISTRIBUTE,
            CASE WHEN A.IS_DISTRIBUTE IS NULL THEN '1' ELSE A.DISTRIBUTE_MODE END SJDJ_DISTRIBUTE_MODE,A.DISTRIBUTE_ACCOUNT
            FROM DUAL LEFT JOIN TA_SP_DOCKING_APPROVE A ON A.APPROVE_ID = :NEW.APPROVE_ID;

        ELSE

            UPDATE SUPERVISE.TA_SP_INSTANCE SET (INSTANCE_CODE,APPROVE_CODE,INSTANCE_NAME,INSTANCE_PY,ACCEPT_NAME,
            ACCEPT_TIME,END_NAME,END_TIME,APPLY_ID,APPLY_TYPE,APPLY_NAME,ORG_ID,AREA_CODE,PROJECT_STATE,QUEUE_CODE,QUERY_CODE,
            NOTACCEPT_REASON,CORRECTION_TIME,APPROVE_ID,INSTANCE_SOURCE,SUBMIT_TIME,REMARK,PRE_REASON,APPROVE_NAME,ACCEPT_ID,END_ID,
            ORG_NAME,CUR_TACHE,IS_SENDRESULT,RZ_APPLY_ID,IS_WLTS,TRANSACTOR_ID,IS_EXCHANGE,
            ACCEPT_ORG_ID,ACCEPT_AREA_CODE,IS_HELPAGENCY,MOD_FLAG,PRETRIAL_TIME,BATCH_ID,DUE_TIME,
            ORG_SOCIAL_CREDIT_NO,APPLYER_TYPE,RESULT_TYPE,RIGHTS_CODE,TASKHANDLEITEM,TRANS_TYPE,TRANSACTION_FROM,LOCALCATALOGCODE,
            LOCALTASKCODE,VERSION_NUM)
            =(SELECT :NEW.INSTANCE_CODE,:NEW.APPROVE_CODE,:NEW.INSTANCE_NAME,:NEW.INSTANCE_PY,:NEW.ACCEPT_NAME,
            :NEW.ACCEPT_TIME,:NEW.END_NAME,:NEW.END_TIME,:NEW.APPLY_ID,:NEW.APPLY_TYPE,:NEW.APPLY_NAME,:NEW.ORG_ID,:NEW.AREA_CODE,:NEW.PROJECT_STATE,:NEW.QUEUE_CODE,:NEW.QUERY_CODE,
            :NEW.NOTACCEPT_REASON,:NEW.CORRECTION_TIME,:NEW.APPROVE_ID,:NEW.INSTANCE_SOURCE,:NEW.SUBMIT_TIME,:NEW.REMARK,:NEW.PRE_REASON,:NEW.APPROVE_NAME,:NEW.ACCEPT_ID,:NEW.END_ID,
            :NEW.ORG_NAME,:NEW.CUR_TACHE,:NEW.IS_SENDRESULT,:NEW.RZ_APPLY_ID,:NEW.IS_WLTS,:NEW.TRANSACTOR_ID,'N',
            :NEW.ACCEPT_ORG_ID,:NEW.ACCEPT_AREA_CODE,:NEW.IS_HELPAGENCY,'N',:NEW.PRETRIAL_TIME,:NEW.BATCH_ID,:NEW.DUE_TIME,
            :NEW.ORG_SOCIAL_CREDIT_NO,:NEW.APPLYER_TYPE,:NEW.RESULT_TYPE,:NEW.RIGHTS_CODE,:NEW.TASKHANDLEITEM,:NEW.TRANS_TYPE,:NEW.TRANSACTION_FROM,:NEW.LOCALCATALOGCODE,
            :NEW.LOCALTASKCODE,:NEW.VERSION_NUM
            FROM DUAL)
            WHERE INSTANCE_ID = :NEW.INSTANCE_ID;


        END IF;
    END IF;
  --异常处理，将错误日志插入错误日志表中
  exception
  when others then
  errorcode := SQLCODE; -- ORA 错误日志号
  errorinfo := SQLERRM; -- ORA 错误详细
  insert into TA_TIR_DATA_EXCEPTION(errcode,errmsg,errtir,tabkey)
  values(errorcode,errorinfo,'TRI_TA_SP_INSTANCE',:NEW.INSTANCE_ID);

END TRI_TA_SP_INSTANCE;
/



--将并联分发的办件触发到总库
update hncs_creatorepp_new.ta_sp_instance t set t.org_name = t.org_name where t.project_state = '21';
commit;